Add accident severity filter to heat map
hasadna/anyway pull request #1502
Opened 2020-10-07 15:09 UTC by shakedzy

2020-10-07 20:45 UTC, BarVolunteering requested changes

2020-10-07 20:45 UTC, BarVolunteering commented on anyway/infographics_utils.py
> +    accidents_heat_map_filters['accident_severity'] = [1, 2]
Can you please change the numbers 1,2 to consts of the accident severity

2020-10-07 21:24 UTC, atalyaalon commented
@shakedzy did you test this?

2020-10-07 21:25 UTC, atalyaalon commented
@shakedzy looks very good BTW :)

2020-10-07 21:26 UTC, atalyaalon reviewed
Looks good to me, just the the consts to the BE constants file https://github.com/hasadna/anyway/blob/dev/anyway/backend_constants.py
(You can use ACCIDENT_SEVERITY_DEADLY const and add another for SEVERE)

2020-10-08 20:41 UTC, shakedzy commented
@atalyaalon - yes, I tested it. Replaced numbers with constants.

2020-10-10 12:29 UTC, merged