Changed title + logic of AccidentCountByDriverTypeWidget
hasadna/anyway pull request #2147
Opened 2022-03-19 09:39 UTC by shaysw

- Changed title to not include section name
- Added filtering to include only drivers

2022-03-19 11:26 UTC, ziv17 commented on anyway/widgets/suburban_widgets/accident_count_by_driver_type_widget.py
> +            filters=filters,
It looks like the filter is only on dates (and not for location).

2022-03-29 14:13 UTC, atalyaalon requested changes
@shaysw looks good! Thanks!
Added 2 comments.

2022-03-29 14:13 UTC, atalyaalon commented on anyway/widgets/suburban_widgets/accident_count_by_driver_type_widget.py
> +        filters["involved_type"] = [1,2]
looks good, perhaps we should add it to our constants (backend_constants.py file) ?

2022-04-19 21:26 UTC, atalyaalon commented
title modification made here: https://github.com/hasadna/anyway/pull/2171

2022-04-19 21:26 UTC, atalyaalon commented
title modification made here: https://github.com/hasadna/anyway/pull/2171

2022-05-13 07:29 UTC, atalyaalon commented
Closing this one, solved in https://github.com/hasadna/anyway/pull/2189/files

2022-05-13 07:29 UTC, closed without merging